version: "3.7"

services:
  elasticsearch_7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: trial
      ELASTIC_PASSWORD: changeme
    restart: unless-stopped
