name: Tests
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 15, 16 ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Start docker
        run: docker compose up -d

      - name: Install npm dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Build package
        run: npx nx build core

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test
